<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="filtering" nsURI="http://www.polarsys.org/capella/filtering/6.0.0"
    nsPrefix="filtering">
  <eAnnotations source="http://www.polarsys.org/kitalpha/emde/1.0.0/extension">
    <details key="extensibleProviderFactory" value="true"/>
    <details key="childCreationExtenders" value="true"/>
    <details key="useUUIDs" value="true"/>
    <details key="useIDAttributes" value="false"/>
  </eAnnotations>
  <eAnnotations source="http://www.polarsys.org/kitalpha/dsl/2007/dslfactory">
    <details key="extensibleProviderFactory" value="true"/>
    <details key="childCreationExtenders" value="true"/>
    <details key="useUUIDs" value="true"/>
    <details key="useIDAttributes" value="false"/>
  </eAnnotations>
  <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
    <details key="description"/>
    <details key="usage guideline"/>
    <details key="used in levels"/>
    <details key="usage examples"/>
    <details key="constraints"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="FilteringModel" eSuperTypes="platform:/plugin/org.polarsys.capella.core.data.gen/model/CapellaCore.ecore#//NamedElement platform:/plugin/org.polarsys.kitalpha.emde/model/eMDE.ecore#//ElementExtension">
    <eAnnotations source="http://www.polarsys.org/kitalpha/emde/1.0.0/constraint">
      <details key="ExtendedElement" value="http://www.polarsys.org/capella/core/modeller/6.0.0#//SystemEngineering"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description"/>
      <details key="usage guideline"/>
      <details key="used in levels"/>
      <details key="usage examples"/>
      <details key="constraints"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedFilteringCriteria"
        upperBound="-1" eType="#//FilteringCriterion" containment="true">
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description"/>
        <details key="usage guideline"/>
        <details key="used in levels"/>
        <details key="usage examples"/>
        <details key="constraints"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedFilteringCriterionPkgs"
        upperBound="-1" eType="#//FilteringCriterionPkg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedVariabilityFeatures"
        upperBound="-1" eType="#//FilteringCriterion" changeable="false" containment="true">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="deprecated" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FilteringCriterion" eSuperTypes="platform:/plugin/org.polarsys.capella.core.data.gen/model/CapellaCore.ecore#//NamedElement">
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description"/>
      <details key="usage guideline"/>
      <details key="used in levels"/>
      <details key="usage examples"/>
      <details key="constraints"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FilteringCriterionSet" abstract="true"
      eSuperTypes="platform:/plugin/org.polarsys.capella.core.data.gen/model/CapellaCore.ecore#//NamedElement">
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description"/>
      <details key="usage guideline"/>
      <details key="used in levels"/>
      <details key="usage examples"/>
      <details key="constraints"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filteringCriteria" upperBound="-1"
        eType="#//FilteringCriterion">
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description"/>
        <details key="usage guideline"/>
        <details key="used in levels"/>
        <details key="usage examples"/>
        <details key="constraints"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variabilityFeatures" upperBound="-1"
        eType="#//FilteringCriterion" changeable="false">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="deprecated" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FilteringResults" eSuperTypes="platform:/plugin/org.polarsys.capella.core.data.gen/model/CapellaCore.ecore#//NamedElement platform:/plugin/org.polarsys.kitalpha.emde/model/eMDE.ecore#//ElementExtension">
    <eAnnotations source="http://www.polarsys.org/kitalpha/emde/1.0.0/constraint">
      <details key="ExtendedElement" value="http://www.polarsys.org/capella/core/modeller/6.0.0#//SystemEngineering"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description"/>
      <details key="usage guideline"/>
      <details key="used in levels"/>
      <details key="usage examples"/>
      <details key="constraints"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filteringResults" upperBound="-1"
        eType="#//AbstractFilteringResult" containment="true">
      <eAnnotations source="http://www.polarsys.org/capella/semantic"/>
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="description"/>
        <details key="usage guideline"/>
        <details key="used in levels"/>
        <details key="usage examples"/>
        <details key="constraints"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedFilteringResultPkgs"
        upperBound="-1" eType="#//FilteringResultPkg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configurations" upperBound="-1"
        eType="#//FilteringResult" changeable="false" containment="true">
      <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
        <details key="deprecated" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FilteringResult" eSuperTypes="#//FilteringCriterionSet #//AbstractFilteringResult">
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description"/>
      <details key="usage guideline"/>
      <details key="used in levels"/>
      <details key="usage examples"/>
      <details key="constraints"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssociatedFilteringCriterionSet" eSuperTypes="#//FilteringCriterionSet platform:/plugin/org.polarsys.kitalpha.emde/model/eMDE.ecore#//ElementExtension">
    <eAnnotations source="http://www.polarsys.org/kitalpha/emde/1.0.0/constraint">
      <details key="ExtendedElement" value="http://www.polarsys.org/capella/core/core/6.0.0#//CapellaElement"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description"/>
      <details key="usage guideline"/>
      <details key="used in levels"/>
      <details key="usage examples"/>
      <details key="constraints"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreationDefaultFilteringCriterionSet"
      eSuperTypes="#//FilteringCriterionSet platform:/plugin/org.polarsys.kitalpha.emde/model/eMDE.ecore#//ElementExtension">
    <eAnnotations source="http://www.polarsys.org/kitalpha/emde/1.0.0/constraint">
      <details key="ExtendedElement" value="http://www.polarsys.org/capella/core/modeller/6.0.0#//SystemEngineering "/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/kitalpha/ecore/documentation">
      <details key="description"/>
      <details key="usage guideline"/>
      <details key="used in levels"/>
      <details key="usage examples"/>
      <details key="constraints"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FilteringResultPkg" eSuperTypes="platform:/plugin/org.polarsys.capella.core.data.gen/model/CapellaCore.ecore#//Namespace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedFilteringResults"
        upperBound="-1" eType="#//AbstractFilteringResult" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedFilteringResultPkgs"
        upperBound="-1" eType="#//FilteringResultPkg" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FilteringCriterionPkg" eSuperTypes="platform:/plugin/org.polarsys.capella.core.data.gen/model/CapellaCore.ecore#//Namespace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedFilteringCriteria"
        upperBound="-1" eType="#//FilteringCriterion" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedFilteringCriterionPkgs"
        upperBound="-1" eType="#//FilteringCriterionPkg" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComposedFilteringResult" eSuperTypes="#//AbstractFilteringResult">
    <eStructuralFeatures xsi:type="ecore:EReference" name="UnionFilteringResultSet"
        eType="#//UnionFilteringResultSet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IntersectionFilteringResultSet"
        eType="#//IntersectionFilteringResultSet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ExclusionFilteringResultSet"
        eType="#//ExclusionFilteringResultSet" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FilteringResultSet" eSuperTypes="platform:/plugin/org.polarsys.capella.core.data.gen/model/CapellaCore.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filteringResults" upperBound="-1"
        eType="#//AbstractFilteringResult"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractFilteringResult" abstract="true"
      eSuperTypes="platform:/plugin/org.polarsys.capella.core.data.gen/model/CapellaCore.ecore#//NamedElement">
    <eOperations name="computeFilteringCriterionSet" eType="#//FilteringCriterionSet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnionFilteringResultSet" eSuperTypes="#//FilteringResultSet"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExclusionFilteringResultSet" eSuperTypes="#//FilteringResultSet"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntersectionFilteringResultSet" eSuperTypes="#//FilteringResultSet"/>
</ecore:EPackage>
